# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp -p:PublishProfile=FolderProfile

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
          # Artifact name
          name: GaAspCore
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{env.DOTNET_ROOT}}/myapp
          # The desired behavior if no files are found using the provided path.           